flask_app/views/answer_question.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint, jsonify
from flask_app import models
from flask_app import db
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user


answer_question_module = Blueprint("answer_question", __name__)




@answer_question_module.route("/answer_question",methods=['GET'])
def answer_question_get(questions):
    return render_template('answer_question.html',questions=questions)



@answer_question_module.route("/answer",methods=['POST'])
def answer():
    print("答合わせ",request.json,flush=True)
    question=models.Question.query.filter(models.Question.questionid == request.json['questionid']).first()
    # print(jsonify(question))
    is_correct=request.json['answer']==question.answer
    
    if(question.correctcount is None):
        question.correctcount=0
    if(question.count is None):
        question.count=0

    question.count+=1

    if(is_correct):
        question.correctcount+=1
    db.session.commit()
    return  {'questionid':question.questionid,'answer': question.answer,'is_correct':is_correct}

flask_app/views/battle.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user
from flask_app import models
from flask_app import db,socketio
from flask_socketio import SocketIO, send, emit ,join_room,leave_room, close_room, rooms, disconnect, ConnectionRefusedError
from flask_cors import CORS
import uuid
from flask_app.views.lobby import rooms_data
import random
import json
battle_module = Blueprint("battle", __name__)

@socketio.on('game_start')
def message(msg):
    print(msg,flush=True)
    room_id=msg['room_id']
    rooms_data[room_id]["status"]="in_progress"
    socketio.emit('add_log', {'text': "ゲーム開始"} ,room=room_id)
    socketio.sleep(1)
    socketio.emit('redirect', {'url': f"battle/{room_id}"},room=room_id)
    questions = quastions_get(room_id)
    print(questions,flush=True)
    socketio.sleep(1)
    socketio.emit('add_log', {'text': f"ゲーム開始"} ,room=room_id)
    rooms_data[room_id]["score"]={}
    for user in rooms_data[room_id]["members"]:
        rooms_data[room_id]["score"][user]=0
    update_ranking(room_id)
    for question in questions:
        print(f"問題:{question.questiontext}",flush=True)
        rooms_data[room_id]["questionid"]=question.questionid
        rooms_data[room_id]["correct_order"]=0
        # socketio.emit('add_log', {'text': f"問題:{question.questiontext}"} ,room=room_id)
        question_text = question.questiontext
        answer_correct = question.answer
        # 選択式問題なら選択肢も表示させる
        if question.questionformat == 1:
            answers_json = json.loads(question.answer)
            choices = [answers_json[key] for key in ["choice_correct", "choice_incorrect1", "choice_incorrect2", "choice_incorrect3"]]
            choice_map = [x for x in range(len(choices))]
            rooms_data[room_id]["choice_map"] = choice_map
            random.shuffle(choice_map)
            for i in range(len(choices)):
                choice = choice_map.index(i)
                # question_text += "<br>{}. {}".format(i + 1, choices[choice])
                question_text += f"<button onclick='choiceanswer(\"{choices[choice]}\")' name='choicebutton'>{choices[choice]}</button>"
            answer_correct = answers_json["choice_correct"]

        socketio.emit('question', {'question_text':question_text,'questionforat':question.questionformat,'answer':question.answer}, room=room_id)
        for i in range(10,0,-1):
            socketio.emit('timer', i ,room=room_id)
            socketio.sleep(1)
        socketio.emit('add_log', {'text': f"答え:{answer_correct}"} ,room=room_id)
        socketio.sleep(1)
    socketio.emit('add_log', {'text': f"終わりです<a href=\"{ url_for('index.index_get') }\" >戻る</a>"} ,room=room_id)
    rooms_data[room_id]["status"]="finish"
    # socketio.emit('question',"おわり" ,room=room_id)
    print(url_for('lobby.room_get'),flush=True)


@socketio.on('send_answer')
def message(msg):
    print(msg,flush=True)
    room_id=msg['room_id']
    username=msg['username']
    question=models.Question.query.filter(models.Question.questionid ==  rooms_data[f"{room_id}"]["questionid"]).first()
    is_correct=msg['answer']==question.answer
    print(f"{is_correct},{msg['answer']},{question.answer}",flush=True)
    if question.questionformat == 0:
        is_correct=msg['answer']==question.answer
    if question.questionformat == 1:
        is_correct=msg['answer']==json.loads(question.answer)["choice_correct"]
    # else:
    #     correct_choice = rooms_data[room_id]["choice_map"][0] + 1
    #     is_correct = msg["answer"] == str(correct_choice)
    log='🙆‍♂️' if is_correct else '🙅'
    if( is_correct):
        rooms_data[room_id]["correct_order"]+=1
        addpoint=1
        if(rooms_data[room_id]["correct_order"]==1):
            addpoint=10
        if(rooms_data[room_id]["correct_order"]==2):
            addpoint=5
        if(rooms_data[room_id]["correct_order"]==3):
            addpoint=2
        rooms_data[room_id]["score"][username]+=addpoint
        update_ranking(room_id)
        log+=f"+{addpoint}points"
        # socketio.emit('correct', "正解" )  

    if(question.correctcount is None):
        question.correctcount=0
    if(question.count is None):
        question.count=0

    question.count+=1

    if(is_correct):
        question.correctcount+=1
    db.session.commit()

    # if(is_correct):
    #     msg['answer']="----"
    socketio.emit('post_answer', {'username':username,'answer':msg['answer'],'is_correct':is_correct},room=msg['room_id'])  

def update_ranking(room_id):
    ranking= dict(sorted( rooms_data[room_id]["score"].items(), key=lambda x: x[1], reverse=True))
    socketio.emit('update_ranking',ranking,room=room_id)  


@battle_module.route("/rooms/battle/<id>",methods=['GET'])
def battles_get(id):
    room_id=id
    return render_template('battle.html',room_id=room_id)


def quastions_get(room_id):
    questions = []
    for questionsetid in  rooms_data[room_id]["question_set"]:
        questions_set = models.Question.query.filter_by(questionsetid=questionsetid).all()
        for question in questions_set:
            if(question not in questions):
                questions.append(question)
            print(question.questionid,flush=True)
    random.shuffle(questions)
    # questions = questions[:10]
    return questions


# #ユーザーの奴全部とる奴、没
# def quastions_get(room_id):
#     questions = []
#     for username in rooms_data[room_id]["members"]:
#         user = models.Account.query.filter_by(name=username).first()
#         if user:
#             print(user.id,flush=True)
#             questionsets = models.Questionset.query.filter_by(questionsetowner=user.id).all()
#             for questionset in questionsets:
#                 print(questionset.questionsetid,flush=True)
#                 questions_in_set = models.Question.query.filter_by(questionsetid=questionset.questionsetid).all()
#                 for question in questions_in_set:
#                     if(question not in questions):
#                         questions.append(question)
#                     print(question.questionid,flush=True)
#     random.shuffle(questions)
#     # questions = questions[:10]
#     return questions

flask_app/views/create_question.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint
from flask_app import models
from flask_app import db
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user
import json
create_question_module = Blueprint("create_question", __name__)


@create_question_module.route("/question/<id>",methods=['GET'])
def create_question_get(id):
    question = models.Question.query.filter_by(questionid=id).one_or_none()
    question_set_name = models.Questionset.query.filter_by(questionsetid=question.questionsetid).one_or_none().questionsetitle
    selection =None
    if(question.questionformat==1):
        selection = json.loads(question.answer)

    return render_template('create_question.html', id=id,question=  question,selection=selection,question_set_name=question_set_name)

@create_question_module.route("/question_delete",methods=['POST'])
def question_delete():
    print( request.json['questionid'],"削除",flush=True)
    question = models.Question.query.filter_by(questionid=request.json['questionid']).one_or_none()

    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('questions_set.questions_get', id=question.questionsetid))

@create_question_module.route("/question/<id>",methods=['POST'])
def create_question_post(id):
    print("問題が変更",flush=True)
    question = models.Question.query.filter_by(questionid=id).one_or_none()
    if question == None:
        return Response(response="<h1>404 Not found<h1/>create_question_module", status=404)
    question.questiontext=request.form["question"]
    print(request.form.get("type"),flush=True)
    if(request.form.get("type")=="text"):
        question.questionformat=0
        question.answer=request.form["answer"]
    if(request.form.get("type")=="choice"):
        question.questionformat=1
        question.answer=json.dumps({"choice_correct":request.form["choice_correct"],
                                    "choice_incorrect1":request.form["choice_incorrect1"],
                                    "choice_incorrect2":request.form["choice_incorrect2"],
                                    "choice_incorrect3":request.form["choice_incorrect2"]})
        
    print(question.answer,flush=True)
    db.session.add(question)
    db.session.commit()
    print(question.questionsetid,flush=True)
    return redirect(url_for('questions_set.questions_get', id=question.questionsetid))

flask_app/views/login.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user
from flask_app import models
from flask_app import db
# import uuid
# from flask_app import app

# from main import login

# login = LoginManager(app)
# @login.user_loader
# def load_user(id):
#     # ログイン機能からidを受け取った際、DBからそのユーザ情報を検索し、返す
#     return models.User.query.get(int(id))

# login = LoginManager(app)

login_module = Blueprint("login", __name__)




# ログインページの実装
@login_module.route('/login', methods=['GET'])
def login_get():
  # 現在のユーザーがログイン済みの場合
  if current_user.is_authenticated:
    # トップページに移動
    return redirect(url_for('index.index_get'))
  
  # loginページのテンプレートを返す
  return render_template('login.html')


# メールアドレスとパスワードを受け取り処理を行う
@login_module.route('/login', methods=['POST'])
def login_post():
    print("ログイン",flush=True)
    # メールアドレスをもとにデータベースへ問い合わせる
    # 結果がゼロの時はNoneを返す
    user = models.Account.query.filter_by(name=request.form["username"]).one_or_none()
    
    # ユーザが存在しない or パスワードが間違っている時
    if user is None or not user.check_password(request.form["password"]):
        # メッセージの表示
        flash('メールアドレスかパスワードが間違っています')
        # loginページへリダイレクト
        return redirect(url_for('login.login_get'))

    # ログインを承認
    login_user(user)
    # トップページへリダイレクト
    return redirect(url_for('index.index_get'))







# ログインページの実装
@login_module.route('/signup', methods=['GET'])
def register_get():
  # 現在のユーザーがログイン済みの場合
  if current_user.is_authenticated:
    # トップページに移動
    return redirect(url_for('index.index_get'))
  
  # loginページのテンプレートを返す
  return render_template('create_account.html')


# メールアドレスとパスワードを受け取り処理を行う
@login_module.route('/signup', methods=['POST'])
def register_post():
    user = models.Account(
        name=request.form["new_userid"],
        # id=str(uuid.uuid4())
    )
   
    user.set_password(request.form["new_password"])
    print("登録")
    # オブジェクトをDBに追加
    db.session.add(user)
    # DBへの変更を保存
    db.session.commit()
    return redirect(url_for('index.index_get'))


@login_module.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index.index_get'))

@login_module.route("/users",methods=['GET'])
def users_get():
    # ユーザオブジェクトを全て取得
    users = models.Account.query.all()
    return render_template('users_get.html', users=users)




@login_module.route("/check_exist_userid",methods=['POST'])
def check_exist_userid():

    is_exeist=models.Account.query.filter_by(name = request.json['new_userid']).first() is not None
    print(is_exeist,flush=True)
    # is_exeist=True
    # if(is_exeist):
    return  {'exist':is_exeist}
    # else:
    # return  {'exist':False}

flask_app/views/quastions_set.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint, jsonify
from flask_app import models
from flask_app import db
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user

quastions_set_module = Blueprint("quastions_set", __name__)



@quastions_set_module.route("/quastions_set",methods=['GET'])
def quastions_set_get():
    #TODO:所有者でフィルタする
    quastions_sets = models.Questionset.query.all()
    return render_template('quastions_set.html',quastions_sets= quastions_sets)

@quastions_set_module.route("/quastions_set",methods=['POST'])
def add_questionset():
    request_data = models.Questionset(questionsetitle ="",questionsetowner=current_user.get_id())
    db.session.add(request_data)
    db.session.commit()
    #TODO:ここ直接行けるようにしたい
    return redirect(url_for('quastions_set.add_questionset'))


@quastions_set_module.route("/quastions_set/<id>",methods=['GET'])
def quastions_get(id):
    quastions = models.Question.query.filter_by(questionsetid=id)
    # if  quastions == None:
    #     return Response(response="<h1>404 Not found<h1/>", status=404)
    return render_template('quastions.html',quastions=  quastions)


@quastions_set_module.route("/quastions_set/<id>",methods=['POST'])
def quastions_set(id):
    #TODO:問題タイプここで選ぶ?
    request_data = models.Question(questionsetid=id,questiontext="quiz")
    db.session.add(request_data)
    db.session.commit()
    #TODO:ここ直接行けるようにしたい
    return redirect(url_for('quastions_set.quastions_get', id=id))

flask_app/views/questions_set.py
from flask import Flask, render_template, request, Response, redirect, url_for, flash
from flask import Blueprint, jsonify
from flask_app import models
from flask_app import db
from flask_login import LoginManager, UserMixin, current_user, login_user, login_required, logout_user

questions_set_module = Blueprint("questions_set", __name__)



@questions_set_module.route("/questions_set",methods=['GET'])
def questions_set_get():
   
    questions_sets = models.Questionset.query.filter_by(questionsetowner=current_user.get_id()).all()
    return render_template('questions_set.html',questions_sets= questions_sets)

@questions_set_module.route("/questions_set",methods=['POST'])
def add_questionset():
    request_data = models.Questionset(questionsetitle ="",questionsetowner=current_user.get_id())
    db.session.add(request_data)
    db.session.commit()

    return redirect(url_for('questions_set.questions_get',id=request_data.questionsetid))


@questions_set_module.route("/questions_set/<id>",methods=['GET'])
def questions_get(id):
    questions = models.Question.query.filter_by(questionsetid=id)
    questionsset = models.Questionset.query.filter_by(questionsetid=id).one_or_none()
    # if  questions == None:
    #     return Response(response="<h1>404 Not found<h1/>", status=404)
    # 
    return render_template('questions.html',questions=  questions,questionset=questionsset,can_delete=len(questions.all())==0)

@questions_set_module.route("/questionset_delete",methods=['POST'])
def question_delete():
    print( request.json['questionsetid'],"削除",flush=True)
    question = models.Questionset.query.filter_by(questionsetid=request.json['questionsetid']).one_or_none()

    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('questions_set.questions_get', id=question.questionsetid))

@questions_set_module.route("/questionsettitle_change",methods=['POST'])
def questionsettitle_change():
    print( request.json['questionsetid'],request.json['new_title'],flush=True)
    questionsset = models.Questionset.query.filter_by(questionsetid=request.json['questionsetid']).one_or_none()
    questionsset.questionsetitle=request.json['new_title']
    db.session.add(questionsset)
    db.session.commit()
    return "ok"

@questions_set_module.route("/questions_set/<id>",methods=['POST'])
def questions_set(id):

    request_data = models.Question(questionsetid=id,questiontext="quiz",count=0,correctcount=0)
    db.session.add(request_data)
    db.session.commit()

    return redirect(url_for('create_question.create_question_get', id=  request_data.questionid))

flask_app/templates/SignupPage.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アカウント作成</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .signup-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        .signup-container h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .signup-container input[type="text"],
        .signup-container input[type="password"],
        .signup-container input[type="email"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .signup-container input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            border: none;
            border-radius: 4px;
            color: white;
            font-size: 16px;
            cursor: pointer;
        }

        .signup-container input[type="submit"]:hover {
            background-color: #0056b3;
        }

        .signup-container input[type="submit"]:disabled {
            background-color: #cccccc;
            cursor: not-allowed;
        }
    </style>
</head>

<body>
    <div class="signup-container">
        <h2>アカウント作成</h2>
        <form action="/signup" method="post">
            <label for="new_userid">ユーザーID</label>
            <input type="text" id="new_userid" name="new_userid" required>
            <label for="email">メールアドレス</label>
            <input type="email" id="email" name="email" required>
            <label for="new_password">パスワード</label>
            <input type="password" id="new_password" name="new_password" required>
            <label for="confirm_password">パスワード確認</label>
            <input type="password" id="confirm_password" name="confirm_password" required>
            <input type="submit" value="作成" id="submit" disabled>


        </form>
    </div>
</body>


<script>

    document.getElementById("new_password").addEventListener("input", function () {
        changePasswordForm();
    });
    document.getElementById("confirm_password").addEventListener("input", function () {
        changePasswordForm();
    });
    function changePasswordForm() {
        const new_userid = document.getElementById("new_userid").value;

        const newPassword = document.getElementById("new_password").value;
        const confirmPassword = document.getElementById("confirm_password").value;
        const submitButton = document.getElementById("submit");

        if (new_userid !== "" && newPassword === confirmPassword && newPassword !== "") {

            submitButton.disabled = false;
        } else {
            submitButton.disabled = true;
        }

        // console.log(submitButton.disabled);
    }


</script>

</html>

flask_app/templates/answer_question.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>問題に回答</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>
    <div class="container">
        <nav>
            <ul>
                <li><a href="{{ url_for('login.logout') }}" id="logout-link">ログアウト</a></li>
                <li><a href="{{ url_for('index.index_get') }}">テーマ一覧</a></li>
            </ul>
        </nav>
        <h1 id="quiz-theme">テーマ:</h1>
        <!-- <form id="answer-form"> -->
        <div id="questions-container">

            {% for question in questions%}


            {{question.questionsetid}}-{{question.questionid }}</br>
            {{question.questiontext}}
            <input type="text" id="input_{{question.questionid}}" />
            <button onclick="answer({{question.questionid}})">答合わせ</button>
            <div id="answer_{{question.questionid}}"></div>
            <!-- <div id=""> -->
            <br>
            {% endfor %}

        </div>
        <!-- <input type="submit" value="回答する"> -->
        <!-- </form> -->

        <div id="result"></div>
        <div id="statistics"></div>
    </div>
    <script src="scripts.js"></script>
</body>

</html>
<script>
    function answer(questionid) {
        console.log(questionid);
        input_answer = document.getElementById(`input_${questionid}`).value;
        fetch('/answer', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ questionid: questionid, answer: input_answer })
        })
            .then(response => {
                return response.json();
            })
            .then(json => {
                console.log(json)
                check_answer = document.getElementById(`answer_${questionid}`);
                check_answer.innerHTML = `${json.is_correct}`
            })
            .catch(error => {
                console.log(error.message);
            });
    }
</script>

flask_app/templates/create_question.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>問題作成</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>
    <div class="container">
        <nav>
            <ul>
                <li><a href="{{ url_for('login.logout') }}" id="logout-link">ログアウト</a></li>
                <li><a href="{{ url_for('index.index_get') }}">テーマ一覧</a></li>
                <button onclick="question_delete()">問題を削除</button>
            </ul>
        </nav>
        <h1>問題作成</h1>
        <form id="create-question-form" method="POST">
            <label for="theme">テーマ:</label>
            <input type="text" id="theme" name="theme" value="{{question_set_name}}" required disabled>
            <div id="question-fields">
                <div class="question-block">
                    <label>問題:</label>
                    <textarea name="question" required>{{question.questiontext}}</textarea>
                    <label>形式:</label>
                    <div>
                        <input type="radio" name="type" id="type_text" value="text" />
                        <label class="radio" for="type_text">文字入力式</label>
                        <input type="radio" name="type" id="type_choice" value="choice" />
                        <label class="radio" for="type_choice">選択式</label>
                    </div>
                    <label>解答:</label>
                    <div id="answer_text" style="display: none;">
                        <input type="text" name="answer" value="{{question.answer}}" required>
                    </div>
                    <div id="answer_choice">
                        <label>正解:</label>
                        <input name="choice_correct" type="text" value="{{selection['choice_correct']}}" />
                        <label>不正解1:</label>
                        <input name="choice_incorrect1" type="text" value="{{selection['choice_incorrect1']}}" />
                        <label>不正解2:</label>
                        <input name="choice_incorrect2" type="text" value="{{selection['choice_incorrect1']}}" />
                        <label>不正解3:</label>
                        <input name="choice_incorrect3" type="text" value="{{selection['choice_incorrect3']}}" />
                    </div>
                </div>
            </div>
            <input type="submit" value="作成">
        </form>
    </div>
    <!-- <script src="scripts.js"></script> -->
</body>

<script>
    const radio_choice = document.getElementById("type_choice")
    const radio_text = document.getElementById("type_text")
    const answer_text = document.getElementById("answer_text")
    const answer_choice = document.getElementById("answer_choice")

    function question_delete() {
        fetch('/question_delete', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ questionid: '{{question.questionid}}' })
        })
        window.location.href = "{{ url_for('questions_set.questions_get', id = question.questionsetid) }}"
    }

    window.onload = function () {
        {% if question.questionformat == 0 %}
        radio_text.checked = true
        answer_choice.style.display = "none";
        answer_text.style.display = "block";
        {% else %}
        radio_choice.checked = true
        answer_choice.style.display = "block";
        answer_text.style.display = "none";
        {% endif %}
    }


    radio_choice.onchange = function () {
        console.log("a")
        answer_choice.style.display = "block"
        answer_text.style.display = "none"
    }
    radio_text.onchange = function () {
        console.log("b")
        answer_choice.style.display = "none"
        answer_text.style.display = "block"
    }
</script>

<style>
    label.radio {
        display: inline;
    }
</style>

</html>

flask_app/templates/index.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>クイズ!!!!</title>
</head>


<body>

    {% if current_user.is_authenticated %}
    あなたのユーザネームは{{ current_user.name }}です。
    <h2>ログイン中</h2>
    <a href="logout">ログアウト</a><br>
    {% else %}
    ログインされていません<br>
    <a href="login">ログイン</a><br>
    <a href="signup">サインアップ</a><br>
    {% endif %}
    {% if current_user.is_authenticated %}
    <a href="questions_set">問題セット管理</a><br>
    {% endif %}
    <a href="questions_set_select">問題を解く</a><br>
    <a href="users">ユーザー一覧(デバッグ用後で消す)</a><br>
    <!-- <a href="battle">バトルモード</a><br> -->
    {% if current_user.is_authenticated %}
    <a href="rooms">バトルモード</a><br>
    {% endif %}
</body>

flask_app/templates/quastions.html
<!DOCTYPE html>
<html lang="jp">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.min.css">

<head>
    <meta charset="UTF-8">
    <title>問題一覧</title>
</head>

<body>

    <form method="POST">
        <input type="submit" value="問題を追加">
    </form>
    <table>
        <tr>
            <th>questionid</th>
            <th>questionsetid </th>
            <th>questiontext</th>
            <th>正答率</th>
        </tr>
        {% for quastion in quastions%}
        <tr>
            <td><a href="/quastion/{{ quastion.questionid }}">
                    <p>{{quastion.questionid }}</p>
                </a></td>
            <td>{{quastion.questionsetid}}</td>
            <td>{{quastion.questiontext}}</td>
            <td>{{ quastion.correctcount }}/{{ quastion.count }}</td>

        </tr>
        {% endfor %}
    </table>

</body>

</html>

flask_app/templates/quastions_set.html
<!DOCTYPE html>
<html lang="jp">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.min.css">

<head>
    <meta charset="UTF-8">
    <title>問題一覧</title>
</head>

<body>

    <form method="POST">
        <input type="submit" value="問題セットを作成">
    </form>
    <table>
        <tr>
            <!-- <th>questionsetid</th> -->
            <th>questionsetid</th>
            <th>questionsetitle</th>
            <th>questionsetowner</th>
        </tr>
        {% for quastions_set in quastions_sets%}
        <tr>
            <td><a href="/quastions_set/{{ quastions_set.questionsetid }}">
                    <p>{{quastions_set.questionsetid }}</p>
                </a></td>
            <td>{{ quastions_set.questionsetitle }}</td>
            <td>{{ quastions_set.questionsetowner }}</td>
        </tr>
        {% endfor %}
    </table>

</body>

</html>

flask_app/templates/questions.html
<!DOCTYPE html>
<html lang="jp">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.min.css">

<head>
    <meta charset="UTF-8">
    <title>問題一覧</title>
</head>

<body>

    問題セット名<input type="text" id="questionsettitle" value="{{questionset.questionsetitle}}">
    {% if can_delete %}
    <button onclick="questionset_delete()">問題セットを削除</button>
    {% endif %}
    <form method="POST">
        <input type="submit" value="問題を追加">
    </form>
    <table>
        <tr>
            <th>questionid</th>
            <th>questionsetid </th>
            <th>questiontext</th>
            <th>正答率</th>
        </tr>
        {% for question in questions%}
        <tr>
            <td><a href="/question/{{ question.questionid }}">
                    <p>{{question.questionid }}</p>
                </a></td>
            <td>{{question.questionsetid}}</td>
            <td>{{question.questiontext}}</td>
            <td>{{ question.correctcount }}/{{ question.count }}({{'{:.0f}'.format( question.correctcount /
                question.count*100) }}%)</td>

        </tr>
        {% endfor %}
    </table>

</body>

</html>

<script>

    const questionsetitle = document.getElementById("questionsettitle")
    questionsetitle.addEventListener("change", function () {
        console.log({ questionsetid: '{{ questionset.questionsetid }}', new_title: questionsetitle.value })
        fetch('/questionsettitle_change', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ questionsetid: '{{ questionset.questionsetid }}', new_title: questionsetitle.value })
        })

    });
    function questionset_delete() {
        fetch('/questionset_delete', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ questionsetid: '{{questionset.questionsetid}}' })
        })
        window.location.href = "{{ url_for('questions_set.questions_set_get') }}"
    }
</script>